# .install_dependencies:
#   before_script:
build-job:
  tags:
    - mac
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: normal
    GIT_SUBMODULE_DEPTH: 1
  script:
    - mkdir -p build-out && cd build-out
    - cmake ..
    - VERBOSE=1 make
